export enum UF {
  AC = 'AC',
  AL = 'AL',
  AM = 'AM',
  AP = 'AP',
  BA = 'BA',
  CE = 'CE',
  DF = 'DF',
  ES = 'ES',
  GO = 'GO',
  MA = 'MA',
  MG = 'MG',
  MS = 'MS',
  MT = 'MT',
  PA = 'PA',
  PB = 'PB',
  PE = 'PE',
  PI = 'PI',
  PR = 'PR',
  RN = 'RN',
  RO = 'RO',
  RR = 'RR',
  RJ = 'RJ',
  RS = 'RS',
  SC = 'SC',
  SE = 'SE',
  SP = 'SP',
  TO = 'TO',
}

export const ufLabels: { [key in UF]: string } = {
  [UF.RO]: 'Rondônia',
  [UF.AC]: 'Acre',
  [UF.AM]: 'Amazonas',
  [UF.RR]: 'Roraima',
  [UF.PA]: 'Pará',
  [UF.AP]: 'Amapá',
  [UF.TO]: 'Tocantins',
  [UF.MA]: 'Maranhão',
  [UF.PI]: 'Piauí',
  [UF.CE]: 'Ceará',
  [UF.RN]: 'Rio Grande do Norte',
  [UF.PB]: 'Paraíba',
  [UF.PE]: 'Pernambuco',
  [UF.AL]: 'Alagoas',
  [UF.SE]: 'Sergipe',
  [UF.BA]: 'Bahia',
  [UF.MG]: 'Minas Gerais',
  [UF.ES]: 'Espírito Santo',
  [UF.RJ]: 'Rio de Janeiro',
  [UF.SP]: 'São Paulo',
  [UF.PR]: 'Paraná',
  [UF.SC]: 'Santa Catarina',
  [UF.RS]: 'Rio Grande do Sul',
  [UF.MS]: 'Mato Grosso do Sul',
  [UF.MT]: 'Mato Grosso',
  [UF.GO]: 'Goiás',
  [UF.DF]: 'Distrito Federal',
};
